//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aclik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aclik()
        {
            this.AclikDosya = new HashSet<AclikDosya>();
        }
    
        public int Id { get; set; }
        public string Kapak { get; set; }
        public Nullable<int> Ayid { get; set; }
        public Nullable<int> Yilid { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        public virtual Ay Ay { get; set; }
        public virtual Yil Yil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AclikDosya> AclikDosya { get; set; }
    }
}
