//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AclikDosya
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<int> AclikID { get; set; }
    
        public virtual Aclik Aclik { get; set; }
    }
}
