//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltMenu
    {
        public int Id { get; set; }
        public string AdTR { get; set; }
        public string AdEn { get; set; }
        public string Link { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<bool> YeniSekme { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
