//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDevlet
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string IsyeriUnvan { get; set; }
        public string TC { get; set; }
        public string Email { get; set; }
        public string CinsiyetId { get; set; }
        public Nullable<System.DateTime> UyelikTarihi { get; set; }
        public string Telefon { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
    }
}
