//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber_
    {
        public int Id { get; set; }
        public string BaslikTR { get; set; }
        public string BaslikEN { get; set; }
        public string texteditorTR { get; set; }
        public string texteditorEN { get; set; }
        public string Kapak { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string PDF { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<System.DateTime> BitTarih { get; set; }
        public Nullable<bool> Ulusal { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        public virtual HaberTur HaberTur { get; set; }
    }
}
