//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int Id { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> SubeID { get; set; }
        public string BaslikTR { get; set; }
        public string BaslikEN { get; set; }
        public string AdTR { get; set; }
        public string AdEN { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Telefon2 { get; set; }
        public string Faks { get; set; }
        public string EPosta { get; set; }
        public Nullable<bool> Sil { get; set; }
        public string Unvan { get; set; }
        public Nullable<int> ilID { get; set; }
        public string Foto { get; set; }
    
        public virtual IL IL { get; set; }
        public virtual iletisimTur iletisimTur { get; set; }
        public virtual Subeler Subeler { get; set; }
    }
}
