//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.AltMenu1 = new HashSet<AltMenu>();
        }
    
        public int Id { get; set; }
        public string AdTR { get; set; }
        public string AdEn { get; set; }
        public string Link { get; set; }
        public Nullable<bool> YeniSekme { get; set; }
        public Nullable<bool> AltMenu { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AltMenu> AltMenu1 { get; set; }
    }
}
