//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOLEYIS_Entities : DbContext
    {
        public TOLEYIS_Entities()
            : base("name=TOLEYIS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aclik> Aclik { get; set; }
        public virtual DbSet<AclikDosya> AclikDosya { get; set; }
        public virtual DbSet<AltMenu> AltMenu { get; set; }
        public virtual DbSet<AltSlider> AltSlider { get; set; }
        public virtual DbSet<AnlasmaliKurumlar> AnlasmaliKurumlar { get; set; }
        public virtual DbSet<Arsiv> Arsiv { get; set; }
        public virtual DbSet<ArsivGaleri> ArsivGaleri { get; set; }
        public virtual DbSet<Ay> Ay { get; set; }
        public virtual DbSet<BolgeTemsilcilik> BolgeTemsilcilik { get; set; }
        public virtual DbSet<Calisanlarimiz> Calisanlarimiz { get; set; }
        public virtual DbSet<EDevlet> EDevlet { get; set; }
        public virtual DbSet<Enflasyon> Enflasyon { get; set; }
        public virtual DbSet<FaydaliLinkler> FaydaliLinkler { get; set; }
        public virtual DbSet<FotoKategori> FotoKategori { get; set; }
        public virtual DbSet<Galeri> Galeri { get; set; }
        public virtual DbSet<Galeri_> Galeri_ { get; set; }
        public virtual DbSet<GaleriFoto> GaleriFoto { get; set; }
        public virtual DbSet<GaleriTur> GaleriTur { get; set; }
        public virtual DbSet<GenelMerkez> GenelMerkez { get; set; }
        public virtual DbSet<Haber> Haber { get; set; }
        public virtual DbSet<Haber_> Haber_ { get; set; }
        public virtual DbSet<HaberGaleri> HaberGaleri { get; set; }
        public virtual DbSet<HaberKategori> HaberKategori { get; set; }
        public virtual DbSet<HaberTur> HaberTur { get; set; }
        public virtual DbSet<Hukuk> Hukuk { get; set; }
        public virtual DbSet<HukukTur> HukukTur { get; set; }
        public virtual DbSet<IL> IL { get; set; }
        public virtual DbSet<ILce> ILce { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<IletisimForm> IletisimForm { get; set; }
        public virtual DbSet<ILTemsilcileri> ILTemsilcileri { get; set; }
        public virtual DbSet<iletisimTur> iletisimTur { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<MainSayfa> MainSayfa { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MobilIslem> MobilIslem { get; set; }
        public virtual DbSet<Nurer> Nurer { get; set; }
        public virtual DbSet<NurerCalisan> NurerCalisan { get; set; }
        public virtual DbSet<NurerSoruCevap> NurerSoruCevap { get; set; }
        public virtual DbSet<Orgutlu> Orgutlu { get; set; }
        public virtual DbSet<Pratik> Pratik { get; set; }
        public virtual DbSet<PratikBilgiler> PratikBilgiler { get; set; }
        public virtual DbSet<PratikDosya> PratikDosya { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sayfa> Sayfa { get; set; }
        public virtual DbSet<SayfaYetki> SayfaYetki { get; set; }
        public virtual DbSet<SiteUyelik> SiteUyelik { get; set; }
        public virtual DbSet<SonKonusma> SonKonusma { get; set; }
        public virtual DbSet<SoruCevap> SoruCevap { get; set; }
        public virtual DbSet<Subeler> Subeler { get; set; }
        public virtual DbSet<SubeTemsilci> SubeTemsilci { get; set; }
        public virtual DbSet<TefeTufe> TefeTufe { get; set; }
        public virtual DbSet<TefeTufeDosya> TefeTufeDosya { get; set; }
        public virtual DbSet<Toleyis> Toleyis { get; set; }
        public virtual DbSet<UstSlider> UstSlider { get; set; }
        public virtual DbSet<UyeSay> UyeSay { get; set; }
        public virtual DbSet<UyeSayisiManuel> UyeSayisiManuel { get; set; }
        public virtual DbSet<Yil> Yil { get; set; }
        public virtual DbSet<Yonetim> Yonetim { get; set; }
        public virtual DbSet<YonetimUnvan> YonetimUnvan { get; set; }
        public virtual DbSet<Ziyaret> Ziyaret { get; set; }
    }
}
