//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurer
    {
        public int Id { get; set; }
        public string BaslikTR { get; set; }
        public string BaslikEN { get; set; }
        public string texteditorTR { get; set; }
        public string texteditorEN { get; set; }
        public string Soru1 { get; set; }
        public string Cevap1 { get; set; }
        public string Soru2 { get; set; }
        public string Cevap2 { get; set; }
        public string Soru3 { get; set; }
        public string Cevap3 { get; set; }
        public string Soru4 { get; set; }
        public string Cevap4 { get; set; }
        public string Soru5 { get; set; }
        public string Cevap5 { get; set; }
        public string Ad1 { get; set; }
        public string Telefon1 { get; set; }
        public string Eposta1 { get; set; }
        public string Ad2 { get; set; }
        public string Telefon2 { get; set; }
        public string Eposta2 { get; set; }
        public string Ad3 { get; set; }
        public string Telefon3 { get; set; }
        public string Eposta3 { get; set; }
        public string Ad4 { get; set; }
        public string Telefon4 { get; set; }
        public string Eposta4 { get; set; }
        public string Ad5 { get; set; }
        public string Telefon5 { get; set; }
        public string Eposta5 { get; set; }
        public string Ad6 { get; set; }
        public string Telefon6 { get; set; }
        public string Eposta6 { get; set; }
        public Nullable<bool> Sil { get; set; }
        public string GenelAd { get; set; }
        public string GenelTelefon { get; set; }
        public string GenelAdres { get; set; }
    }
}
