//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orgutlu
    {
        public int Id { get; set; }
        public Nullable<int> ilID { get; set; }
        public string Ad { get; set; }
        public string Resim { get; set; }
        public string Website { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> TolId { get; set; }
    
        public virtual IL IL { get; set; }
    }
}
