//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PratikDosya
    {
        public int Id { get; set; }
        public string Yol { get; set; }
        public Nullable<int> PratikID { get; set; }
    
        public virtual Pratik Pratik { get; set; }
    }
}
