//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubeTemsilci
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Unvan { get; set; }
        public string Resim { get; set; }
        public Nullable<int> SubeId { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        public virtual Subeler Subeler { get; set; }
        public virtual Subeler Subeler1 { get; set; }
    }
}
