//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeSayisiManuel
    {
        public int Id { get; set; }
        public string UyeSayisi { get; set; }
        public string Metin { get; set; }
        public Nullable<bool> Sil { get; set; }
    }
}
