//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOLEYIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetim
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string OzgecmisTR { get; set; }
        public string OzgecmisEN { get; set; }
        public string Gorev { get; set; }
        public string Foto { get; set; }
        public Nullable<int> UnvanID { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        public virtual YonetimUnvan YonetimUnvan { get; set; }
    }
}
